services:
  app1:
    build:
      context: ./app1/next-app/
      dockerfile: Dockerfile
    container_name: nextjs_app1
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3000" # 호스트 3001 포트를 컨테이너 3000 포트에 매핑
    networks:
      - webapps_network

  app2:
    build:
      context: ./app2/next-app/ # app2 폴더의 Dockerfile 사용
      dockerfile: Dockerfile
    container_name: nextjs_app2
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    ports:
      - "3002:3000" # 호스트 3002 포트를 컨테이너 3000 포트에 매핑
    networks:
      - webapps_network

networks:
  webapps_network:
    driver: bridge
